language: python
python:
  - "3.7-dev"
# command to install dependencies
install:
  - pip install pytest==3.7.4 pytest-cov==2.6.1 coveralls
# command to run tests
script:
  - py.test --cov=. .
after_success:
  - coveralls
